version: '3.7'
networks:
  net:

services:

  frontend:
    image: frontend
    environment:
      SERVICE_ADRESS: frontend
      SERVICE_PORT: 4200
    ports:
      - 4200:4200
    networks:
      - net

  service-authentication:
    image: service-authentication
    environment:
      SERVICE_ADRESS: service-authentication
      SERVICE_PORT: 3000
      ports:
        - 3000:3000
    networks:
      - net

  service-message:
    image: service-message
    environment:
      SERVICE_ADRESS: service-message
      SERVICE_PORT: 3000
      ports:
        - 3001:3000
    networks:
      - net
  service-notification:
    image: service-notification
    environment:
      SERVICE_ADRESS: service-notification
      SERVICE_PORT: 3000
      ports:
        - 3002:3000
    networks:
      - net

  service-privateroom:
    image: service-privateroom
    environment:
      SERVICE_ADRESS: service-privateroom
      SERVICE_PORT: 3000
      ports:
        - 3003:3000
    networks:
      - net

  mongodb-authentication:
    image: mongo
    networks:
      - net
    ports:
      -  27017:27017

  mongodb-message:
    image: mongo
    networks:
      - net
    ports:
      - 27020:27017

  mongodb-notification:
    image: mongo
    networks:
      - net
    ports:
      - 27021:27017

  mongodb-privateroom:
    image: mongo
    networks:
      - net
    ports:
      - 27022:27017